services:
  postgres:
    image: postgres:13.3
    container_name: postgres_pomosch
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASS}
    ports:
      - "${DB__PORT}:${DB__DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data:cached

  redis:
    image: redis
    container_name: redis_pomosch
    restart: unless-stopped
    ports:
        - '${REDIS__PORT}:${REDIS__PORT}'

volumes:
  db_data: