services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data:cached
    networks:
      - backend


  bot:
    container_name: database_service
    hostname: database_service
    build: ServiceDatabase/.
    restart: always
    ports:
      - 44044:44044
    command: [
        "/app/service",
        "--config=local.yaml"
    ]
    networks:
      - backend
    depends_on: 
      - postgres


networks:
  backend:
    driver: bridge

volumes:
  db_data: