services:
  postgres:
    container_name: postgres_pomosch
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASS}
    ports:
      - "${DB__PORT}:${DB__DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data:cached
    network_mode: host

  redis:
    image: redis
    container_name: redis_pomosch
    restart: unless-stopped
    ports:
      - '${REDIS__PORT}:${REDIS__PORT}'
    network_mode: host

  backend:
    container_name: backend_pomosch
    build:
      context: .
      dockerfile: Dockerfile
    command: sh /app/start.sh
    tty: true
    env_file:
      - .env
    ports:
      - "${BACKEND_SERVER__PORT}:${BACKEND_SERVER__PORT}"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/research_data:/app/backend/research_data
    network_mode: host


volumes:
  db_data:
