"""photo

Revision ID: f77f39bc22b5
Revises: 
Create Date: 2024-09-15 02:53:26.018534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f77f39bc22b5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column(
            "creation_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_shop",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "creation_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "StaffRole",
                "AdminRole",
                "PartnerRole",
                "VendorRole",
                "SuperUserRole",
                "PersonRole",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column("company", sa.Boolean(), nullable=True),
        sa.Column(
            "creation_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "company_user",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("site", sa.String(), nullable=True),
        sa.Column("inn", sa.String(), nullable=True),
        sa.Column("kpp", sa.String(), nullable=True),
        sa.Column("okpo", sa.String(), nullable=True),
        sa.Column("card_number", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "god_send",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("passport", sa.String(length=256), nullable=False),
        sa.Column("card_number_gods", sa.Integer(), nullable=True),
        sa.Column("card_number", sa.String(length=256), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("city_id", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "ElderlyCategory",
                "KidsCategory",
                "PetsCategory",
                "OtherCategory",
                name="categorygodsend",
            ),
            nullable=False,
        ),
        sa.Column("moderator_id", sa.UUID(), nullable=False),
        sa.Column("check", sa.Boolean(), nullable=True),
        sa.Column("data_check", sa.DateTime(), nullable=True),
        sa.Column(
            "creation_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_god_send_id"), "god_send", ["id"], unique=False)
    op.create_table(
        "natural_user",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("card_number", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "product_basket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product_shop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_photos",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product_shop.id"],
        ),
        sa.PrimaryKeyConstraint("product_id", "photo_id"),
    )
    op.create_table(
        "user_photos",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "photo_id"),
    )
    op.create_table(
        "godsend_photos",
        sa.Column("godsend_id", sa.UUID(), nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["godsend_id"],
            ["god_send.id"],
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photo.id"],
        ),
        sa.PrimaryKeyConstraint("godsend_id", "photo_id"),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("godsend_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "task",
            sa.Enum("Money", "Service", "Product", "Job", name="task"),
            nullable=False,
        ),
        sa.Column("order_sum", sa.Integer(), nullable=False),
        sa.Column(
            "dimension", sa.Enum("Rub", "Pcs", "Man", name="dimension"), nullable=False
        ),
        sa.Column(
            "collect_id",
            sa.Enum("Monthly", "One_time", "Emergency", "General", name="collect"),
            nullable=False,
        ),
        sa.Column("moderator_id", sa.UUID(), nullable=False),
        sa.Column("check", sa.Boolean(), nullable=True),
        sa.Column("data_check", sa.DateTime(), nullable=True),
        sa.Column("text_check", sa.String(), nullable=True),
        sa.Column(
            "creation_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["godsend_id"],
            ["god_send.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_id"), "order", ["id"], unique=False)
    op.create_table(
        "donat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("summa", sa.Float(), nullable=False),
        sa.Column("date_done", sa.DateTime(), nullable=False),
        sa.Column(
            "creation_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_photos",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photo.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "photo_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_photos")
    op.drop_table("donat")
    op.drop_index(op.f("ix_order_id"), table_name="order")
    op.drop_table("order")
    op.drop_table("godsend_photos")
    op.drop_table("user_photos")
    op.drop_table("product_photos")
    op.drop_table("product_basket")
    op.drop_table("natural_user")
    op.drop_index(op.f("ix_god_send_id"), table_name="god_send")
    op.drop_table("god_send")
    op.drop_table("company_user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_table("product_shop")
    op.drop_table("photo")
    # ### end Alembic commands ###
