"""Done

Revision ID: bada3b21b6aa
Revises: 
Create Date: 2024-09-02 02:12:52.698120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bada3b21b6aa"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("godsend_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "task",
            sa.Enum("Money", "Service", "Product", "Job", name="task"),
            nullable=False,
        ),
        sa.Column("order_sum", sa.Integer(), nullable=False),
        sa.Column(
            "dimension", sa.Enum("Rub", "Pcs", "Man", name="dimension"), nullable=False
        ),
        sa.Column(
            "collect_id",
            sa.Enum("Monthly", "One_time", "Emergency", "General", name="collect"),
            nullable=False,
        ),
        sa.Column("moderator_id", sa.UUID(), nullable=False),
        sa.Column("check", sa.Boolean(), nullable=True),
        sa.Column("data_check", sa.DateTime(), nullable=True),
        sa.Column("text_check", sa.String(), nullable=True),
        sa.Column(
            "creation_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["godsend_id"],
            ["god_send.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_id"), "order", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_id"), table_name="order")
    op.drop_table("order")
    # ### end Alembic commands ###
